fix dhcpv6 counters are not cleared on clear command
sonic-net/sonic-dhcp-relay pull request #38
Opened 2023-05-25 16:07 UTC by jcaiMR

### Description of PR
Fix dhcpv6 counters are not cleared after "clear dhcp6relay_counters", or "sonic-db-cli STATE_DB hmset "DHCPv6_COUNTER_TABLE|Vlan1000" {} 0
 
Summary:
Fix https://github.com/sonic-net/sonic-buildimage/issues/14447
dhcpv6 relay counter cached in original relay code, so even we clear counter in STATE_DB, next time when packets come from downlink or uplink ports, counter will be flushed with relay cached data + 1, so the counter flushed back to original data + 1. 

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012
- [x] 202205
Need in 202205 and 202012, need manually double commit because of code conflict. 

### Approach
#### What is the motivation for this PR?
Fix clear counter issue

#### How did you do it?
Remove cache in dhcp_relay code, instead we will read count from STATE_DB then refresh.

#### How did you verify/test it?
test_dhcpv6_relay.py::test_dhcpv6_relay_counter multiple times and with clear counter.

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

2023-05-25 22:51 UTC, vivekrnv requested changes

2023-05-25 22:51 UTC, vivekrnv commented on src/relay.h
> +void initialize_counter(std::shared_ptr<swss::DBConnector> state_db, std::string ifname);
Preferable to be `const std::string&`

2023-05-25 22:51 UTC, vivekrnv commented on src/relay.h
> +void increase_counter(std::shared_ptr<swss::DBConnector> state_db, std::string ifname, uint8_t msg_type);
Preferable to be `const std::string&`

2023-05-25 22:51 UTC, vivekrnv commented on src/relay.cpp
> +        state_db->hset(table_name, type, toString(0));
Shouldn't this be toString(1) since this packet must be accounted for?

2023-05-25 22:51 UTC, vivekrnv commented on src/relay.cpp
>  void sent_msg_increase_counter(relay_config *config, uint8_t msg_type) {
Why do we need this method? i think `increase_counter `can replace `sent_msg_increase_counter` method now.

2023-05-25 22:51 UTC, vivekrnv commented on src/relay.cpp
> +void initialize_counter(std::shared_ptr<swss::DBConnector> state_db, std::string ifname) {
A container restart is supposed to happen if there is a config change or config reload. And so i think its is okay to zero all the counters initially. and then the STATE_DB is reflective of the status of counters seen during the lifetime of the current process.

we anyway have dhcpmon which tracks and dumps counters periodically or when its terminated crct.

Also, what about the stale entries. i.e. if some VLAN is removed and we do a container restart the entries in STATE_DB would remain forever unless clear is called.  During process init, i suggest clearing out the entire `DHCPv6_COUNTER_TABLE` table

2023-05-26 02:23 UTC, jcaiMR commented on src/relay.h
> +void initialize_counter(std::shared_ptr<swss::DBConnector> state_db, std::string ifname);
Agree, thanks for good point.

2023-05-26 20:10 UTC, vivekrnv commented on src/relay.cpp
> +        initialize_counter(vlan.second.state_db, vlan.second.interface);
Changes look good, i also suggest clearing out the entire COUNTERS Table, during init. That'll fix this issue as well `https://github.com/sonic-net/sonic-buildimage/issues/15047`

2023-06-02 19:26 UTC, vivekrnv commented on src/relay.cpp
> +        initialize_counter(vlan.second.state_db, vlan.second.interface);
> https://github.com/sonic-net/sonic-buildimage/issues/15047

Looks like the issue is handled by https://github.com/sonic-net/sonic-utilities/pull/2852, not required to clear DHCPv6_COUNTERS table here. #Resolved

2023-06-02 19:28 UTC, vivekrnv approved these changes

2023-06-05 06:06 UTC, kellyyeh approved these changes

2023-06-05 15:57 UTC, merged